### ISSUE TITLE
Browsersync improvements

### ISSUE THREAD

**Issue by BlackShabat** [justintadlock/mythic#39]
I think it would be nice to add browsersync proxy option into npm run rename or to some other install instruction. Currently it's hardcoded inside webpack.mix.js file as localhost. But usually developers has different local domain for projects

Also I didn't understand why changing css and js files from dist folder has been omitted in browsersync file extensions. Maybe it has some reason?

**Comment by justintadlock** [comment]
I'll let @m-e-h tackle that for now.  I'll leave this open but follow the ticket linked above.

**Comment by atanas-angelov-dev** [comment]
> Also I didn't understand why changing css and js files from dist folder has been omitted in browsersync file extensions. Maybe it has some reason?

AFAIK, the `dist/` directory is entirely automatically generated so you shouldn't be changing those files - you should be changing the source files in `resources/` instead.

**Comment by justintadlock** [comment]
I'm going to close this specific ticket.  If there's one thing I've learned as of late is that people can have all sorts of different BrowserSync settings.  What I've decided is to set a default and leave it at that (for now, at least).

It is expected that theme authors will be editing their `webpack.mix.js` file to customize things to their liking.  BrowserSync is a part of that.

If this gets added as part of the `theme-claim` package, I'll certainly add support for it.

Also, I've separated the `watch` task into `watch` (for watching changes only) and `watch:sync` (for watching + BrowserSync).

And, finally, we've since adjusted the files that are watched with BrowserSync, which should work better now.

---

A secondary idea that we could explore is potentially a theme config file where things like this could be set.  That's probably not going to make the cut for the 1.0 release.  It would also have a wider scope than this ticket.
