### ISSUE TITLE
Creating Pages

### ISSUE THREAD

**Issue by JakeHenshall** [justintadlock/mythic#69]
Hi,

I really like this framework.

What is the best way to start creating extra views?

Would you do: 

front.page.php

```php
<?php

// Load header/* template.
Hybrid\View\display( 'header', Hybrid\Template\hierarchy() );

// Load content/* template.
Hybrid\View\display( 'front-page', Hybrid\Template\hierarchy() );

// Load footer/* template.
Hybrid\View\display( 'footer', Hybrid\Template\hierarchy() );

resources/views/front-page/index.php

```php

// Test Content

Also, how would it be best to create multiple other pages?

I'm sorry if this is a dumb question, but hopefully, you can help out.

Thanks.

**Comment by justintadlock** [comment]
Here's some documentation on what you can do with views:

- https://github.com/justintadlock/mythic/wiki/Views
- https://themehybrid.com/weblog/working-with-the-view-class

If you need help, just post over on our Slack channel or the support forums: https://themehybrid.com/board/forums/hybrid-core

Closing this ticket out since it's a support question rather than a bug or enhancement.
