### ISSUE TITLE
Upgrade to Laravel Mix 4.0.0

### ISSUE THREAD

**Issue by justintadlock** [justintadlock/mythic#70]
Mix version 4.0.0 just got tagged: https://github.com/JeffreyWay/laravel-mix/releases/tag/v4.0.0

This bumps Webpack to 4.  Compiling should be noticeably faster.  This needs to be fully tested to make sure everything is working correctly with our setup.  

It'll also close out https://github.com/justintadlock/mythic/pull/55 because `mix.standaloneSass()` is no longer in 4.0.0.

**Comment by brettsmason** [comment]
Looking into how they are solving the CSS extraction issue with Webpack 4 (which was the reason for the hold up) they are still using Extract Text Webpack Plugin: https://github.com/JeffreyWay/laravel-mix/commit/e76287706d31d19bad1a31a3d3332597e85f03be

However, they have made it pretty clear that it shouldn't be used for CSS in Webpack 4: https://github.com/webpack-contrib/extract-text-webpack-plugin#usage
`Since webpack v4 the extract-text-webpack-plugin should not be used for CSS. Use mini-css-extract-plugin instead.`

Depends how you feel about that. I guess it still works so maybe not a big deal.

**Comment by justintadlock** [comment]
Meant to tag this ticket with the following changeset: https://github.com/justintadlock/mythic/commit/c69e38518d5f52ac643a36da66150428847b4f57

**Comment by lkraav** [comment]
@justintadlock what's the criteria for successfully completing this issue?

**Comment by justintadlock** [comment]
Giving it a few days for testing to make sure no one breaks anything.  Outside of that, it's completed.

**Comment by justintadlock** [comment]
I think we're good to go.
